[project]
name = "okr-reviewer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "xiaofei.yin", email = "xiaofei.yin@nio.com" }
]
requires-python = ">=3.12"
dependencies = [
    "duckdb>=1.3.2",
    "matplotlib>=3.10.5",
    "pandas>=2.3.1",
    "seaborn>=0.13.2",
]

[project.scripts]
okr-reviewer = "okr_reviewer:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
